// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFTest.Models
{
    public partial class TbPageSection
    {
        public int Id { get; set; }
        public int PageId { get; set; }
        public int SectionId { get; set; }

        public virtual TbPage Page { get; set; }
    }
}